# Set style
sns.set(style="whitegrid")

# 1. Line chart (trends in sepal length)
plt.figure(figsize=(10, 5))
sns.lineplot(data=df, x=df.index, y='sepal length (cm)', hue='species')
plt.title("Sepal Length Trends by Species")
plt.xlabel("Sample Index")
plt.ylabel("Sepal Length (cm)")
plt.show()

# 2. Bar chart (mean petal length by species)
plt.figure(figsize=(8, 5))
sns.barplot(data=df, x='species', y='petal length (cm)')
plt.title("Mean Petal Length by Species")
plt.xlabel("Species")
plt.ylabel("Petal Length (cm)")
plt.show()

# 3. Histogram (sepal width distribution)
plt.figure(figsize=(8, 5))
sns.histplot(data=df, x='sepal width (cm)', kde=True, hue='species')
plt.title("Sepal Width Distribution")
plt.xlabel("Sepal Width (cm)")
plt.ylabel("Frequency")
plt.show()

# 4. Scatter plot (sepal length vs. petal length)
plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x='sepal length (cm)', y='petal length (cm)', hue='species')
plt.title("Sepal Length vs. Petal Length")
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Petal Length (cm)")
plt.show()